version: '2'

services:
    db:
        image: clearlinux/mariadb:latest
        restart: always
        command: --bind-address=0.0.0.0
        env_file: 
            - mariadb.env
        ports:
            - "3306:3306"
        networks:
            - laravel-network
        volumes:
            - ./.local/var/lib/mysql:/var/lib/mysql
            - ./.local/var/backups:/var/backups
            - ./.local/var/seeds:/var/seeds
        user: "${USER_ID}:${GROUP_ID}"
    nginx:
        restart: always
        image: clearlinux/nginx:latest
        ports:
            - "8080:80"
        links:
            - laravel
        volumes:
            - ${SRC}:/var/www/html
            - ./laravel.conf:/etc/nginx/conf.d/default.conf
            - ./.local/var/log/nginx/:/var/log/nginx
        networks:
            - laravel-network
    laravel:
        restart: always
        depends_on:
            - db
        build: .
        restart: always
        volumes:
            - ./${SRC}:/var/www/html
        command: php-fpm
        networks:
            - laravel-network
        user: "${USER_ID}:${GROUP_ID}"
        env_file: 
            - laravel.env
networks:
    laravel-network:
        driver: bridge


